apiVersion: v1
kind: Service
metadata:
  name: sign-language-detector-service
spec:
  selector:
    app: sign-language-detector
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
